name: project deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh 
        uses: appleboy/ssh-action@v1
        with:
          host: 121.140.125.176
          username: test
          password: qwer1234
          port: 105
          script: |
            rm -rf ./demo30
            git clone https://github.com/junsun-yeam/distribution.git
            cd ./demo30
            chmod 755 ./gradlew
            ./gradlew bootJar
            docker rm -f back
            docker image prune -f
            docker build --tag whatisjustice/back:latest .
            docker run -d --name back --stop-timeout 15 -p 8080:8080 whatisjustice/back:latest

            
